spring:
  application:
    name: Task Management System
    version: 6.0

  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManagement
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    root: info