spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/AUTHDB
    username: auth_user
    password: password

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true
    enabled: true

server:
  port: 8081